feat(#69): add filter routes support.
Eomm/fastify-overview pull request #90
Opened 2023-10-08 20:48 UTC by drazen04

Hi, I've created support for filtering routes.
I also did a little refactoring on the 'getOverview' function.
Please let me know if there are changes you'd like to see or if you have any general feedback.

2023-10-09 06:41 UTC, Eomm requested changes
Thanks for the PR!

2023-10-09 06:41 UTC, Eomm commented on test/index.test.js
> +  app.get('/to-filter', noop)
Does it work if you move this route in a child context?

```
app.register(function plugin (app, opts, next) {
  app.get('/to-filter', noop)
  next()
})
```

2023-10-09 06:41 UTC, Eomm commented on lib/utils.js
> +function withRoutesFiltered(structure, routesFilterPredicate) {
I think we could collapse this process in the `withEmptyPropsHidden` function.

That one is quite expensive, so it is good to make it more "intelligent"

2023-10-09 06:41 UTC, Eomm commented on lib/utils.js
> +  structure.routes = structure.routes.filter(r => routesFilterPredicate(r.method, r.url, r.prefix))
we filter only the first context and we are ignoring children ones

Take a look here:
https://github.com/Eomm/fastify-overview/blob/main/test/fixture/app-no-source.json

2023-10-09 06:41 UTC, Eomm commented on README.md
> +  routesFilter: function (method, url, prefix) {
I would provide the `routeItem` object instead, so user can filter also on other stuff such as `sourceCode` in case

2023-10-09 06:41 UTC, Eomm commented on index.js
> +    structure = opts && opts.hideEmpty ? withEmptyPropsHidden(structure) : structure
```suggestion
    structure = opts?.hideEmpty ? withEmptyPropsHidden(structure) : structure
```

2023-10-09 07:16 UTC, drazen04 commented on lib/utils.js
> +function withRoutesFiltered(structure, routesFilterPredicate) {
Ok, I had a doubt here: does the routesFilter activate with the "hideEmpty" flag or are they two separate logics?

2023-10-09 07:18 UTC, drazen04 commented
> Thanks for the PR!

Thanks to you for the review :) . I will fix what you point pout as soon as possible.

2023-10-09 20:37 UTC, drazen04 commented on test/index.test.js
> +  app.get('/to-filter', noop)
Yes, It is, but only because I checked only root.routes. Now I added more check on children.

2023-10-10 16:15 UTC, Eomm requested changes

2023-10-10 16:15 UTC, Eomm commented on index.js
> +    return opts?.hideEmpty ? withEmptyPropsHidden(structure, opts) : structure
we can't use the filter without the `hideEmpty` flag here.

Don't be afraid to refactor it to something like:

```
if(opts.hideEmpty || opts.routesFilter) {
  return filterStructure(structure, opts)
}
return structure
```

2023-10-10 16:15 UTC, Eomm commented on lib/utils.js
> +    return withRoutesFiltered(JSON.parse(filterStructure), opts.routesFilter)
this code is not optimized:

- we run `JSON.stringify` that navigates all the json-tree
- then we parse it back to a json object
- then we run a recursive loop on the children

Instead, if you move the logic inside the `JSON.stringify` function, by adding a case check for `key === 'routes'` you can apply the filter to the `value` - and we won't need the recursive loop.

I think this is a good solution.

Here I was using `JSON.stringify` as a hack to navigate the structure without modifying it

2023-10-11 07:01 UTC, drazen04 commented on lib/utils.js
> +    return withRoutesFiltered(JSON.parse(filterStructure), opts.routesFilter)
Totally agree, thanks. 👍

2023-10-14 15:15 UTC, Eomm reviewed
LGTM!

Could you fix the linting and the coverage?

```
ERROR: Coverage for lines (99.26%) does not meet global threshold (100%)
ERROR: Coverage for branches (98.52%) does not meet global threshold (100%)
ERROR: Coverage for statements (99.27%) does not meet global threshold (100%)
----------------------|---------|----------|---------|---------|-------------------
File                  | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------------------|---------|----------|---------|---------|-------------------
All files             |   99.27 |    98.52 |     100 |   99.26 |                   
 fastify-overview     |     100 |      100 |     100 |     100 |                   
  index.js            |     100 |      100 |     100 |     100 |                   
 fastify-overview/lib |   97.91 |    97.14 |     100 |   97.87 |                   
  source-code.js      |     100 |      100 |     100 |     100 |                   
  utils.js            |   97.29 |    96.96 |     100 |   97.29 | 124               
----------------------|---------|----------|---------|---------|-------------------
```

2023-10-16 05:35 UTC, Eomm approved these changes
Thks!

2023-10-16 05:36 UTC, merged